const nome = prompt('Digite seu nome completo')
const dtNascimento = prompt('Digite sua data de nascimento')
let endereco = prompt('Digite seu endereço')
const cpf = prompt('Digite seu CPF')
let escolaridade = prompt('Digite qual sua escolaridade')
let cnh = confirm('Possui CNH?')
let filhos = Number (prompt('Tem quantos filhos?'))
let cargoAtual = prompt('Digite seu cargo atual')
let salario = Number (prompt('Digite seu salário'))
let comissao = confirm('Recebe comissão? Se sim, aperte em confirme, caso não, clique em cancel')
const anoAdmissao = prompt('Digite seu ano de admissão')

console.log('Tipo variável nome', typeof nome)
console.log('Tipo variável dt de nascimento', typeof dtNascimento)
console.log('Tipo variável endereço', typeof endereco)
console.log('Tipo variável cpf', typeof cpf)
console.log('Tipo variável escolaridade', typeof escolaridade)
console.log('Tipo variável cnh', typeof cnh)
console.log('Tipo variável filhos', typeof filhos)
console.log('Tipo variável cargo atual', typeof cargoAtual)
console.log('Tipo variavel salário', typeof salario)
console.log('Tipo variável comissão', typeof comissao)
console.log('Tipo variável ano de admissão', typeof anoAdmissao)

console.log('Funcionário', nome, 'data de nascimento:', dtNascimento, 'endereço:', endereco, 'portador cpf:', cpf, 'Escolaridade:', escolaridade, 'Possui cnh:', cnh, 'Com', filhos, 'filhos', 'Cargo atual:', cargoAtual, 'Salário:', salario, 'Admitido em:', anoAdmissao, 'recebe comissão:' , comissao)